### PR TITLE
Corrected template argument and added linkpost template example

### PR DESCRIPTION
**Pull request by SteveEdson**

### CODE REVIEW

**Comment by imathis** [comment]
Thanks again. You're on a roll! The command can actually take a path from `_templates/` but it's not necessary. I figure some people like the shell auto-complete rather than having to type out `linkpost` every time.

**Comment by SteveEdson** [comment]
No problem :). I think the doc should make it clear that the argument can take sub dirs inside `_templates/`, but the current example fails with:

> No post template found at /MySite/_templates/_templates/linkpost

A lot of people (including myself) will just copy the example command to try it out.

**Comment by imathis** [comment]
Hmm maybe I busted it. Having a look. Thanks!

**Comment by imathis** [comment]
Yep. Turns out… It didn't work properly. I've fixed it though, so thanks!

**Comment by imathis** [comment]
Alright, I've updated the Readme with a note about shell auto-complete. I hope that doesn't reduce the simplicity in reading these docs too much.

**Comment by imathis** [comment]
I just bundled these fixes into a new gem release. Thanks again. :)

**Comment by justinrummel** [comment]
What if the Readme was broken down into sections and then utilized by the Wiki feature in Github?  Would that make it simpler to digest?

**Comment by imathis** [comment]
The Readme will probably be broken down into sections, but I'm not using GitHub's wikis. I have a system that collects documentation for each Octopress project and builds it into a website that I can deploy easily. It's something I'm still working on as I rebuild the Octopress site.

**Pull request merged**
